export const HOME = '/'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const DASHBOARD = '/dashboard'
export const SCHEDULE = '/schedule'
export const HISTORY = '/history'
export const SPECIALISTS = '/specialists'
export const VIDEOCALL = '/videocall'
